parameters:
  - name: publish
    default: false
    type: boolean

jobs:
- job: ModulePublish
  displayName: Publish to PSGallery
  pool:
    type: release
    os: windows
  templateContext:
    inputs:
      - input: pipelineArtifact
        pipeline: AIShellPackagePipeline
        artifactName: drop_module_package
  variables:
    # Disable SBOM, signing, and codeQL for this job
    - name: ob_sdl_sbom_enabled
      value: false
    - name: ob_signing_setup_enabled
      value: false
    - name: ob_sdl_codeql_compiled_enabled
      value: false

  steps:
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        Get-ChildItem '$(Pipeline.Workspace)/*.nupkg' -recurse
    displayName: List nupkg package

  - task: NuGetCommand@2
    displayName: Push AIShell module to PSGallery feed
    condition: and(ne('${{ parameters.publish }}', 'false'), succeeded())
    inputs:
      command: push
      packagesToPush: '$(Pipeline.Workspace)/*.nupkg'
      nuGetFeedType: external
      publishFeedCredentials: PowerShellGallery-dongbow
